import React, { useState } from 'react';
import { api } from '../api';
import { UploadCloud, FileText, CheckCircle, AlertCircle } from 'lucide-react';

const UploadCard = ({ title, endpoint, description, accept }) => {
    const [status, setStatus] = useState('idle'); // idle, uploading, success, error
    const [message, setMessage] = useState('');

    const handleUpload = async (e) => {
        const file = e.target.files[0];
        if (!file) return;

        setStatus('uploading');
        const formData = new FormData();
        formData.append('file', file);

        try {
            const res = await api.uploadFile(endpoint, formData);
            setStatus('success');
            setMessage(res.message);
            // Reset after 3 seconds
            setTimeout(() => { setStatus('idle'); setMessage(''); }, 3000);
        } catch (error) {
            setStatus('error');
            setMessage("Upload failed. Ensure it's a valid CSV.");
        }
    };

    return (
        <div className="bg-pro-card p-6 rounded-xl border border-gray-700 hover:border-pro-accent transition-colors">
            <div className="flex items-start justify-between mb-4">
                <div>
                    <h3 className="text-xl font-bold text-white">{title}</h3>
                    <p className="text-sm text-gray-400 mt-1">{description}</p>
                </div>
                <div className={`p-2 rounded-lg ${status === 'success' ? 'bg-pro-success/20 text-pro-success' : 'bg-gray-800 text-gray-400'}`}>
                    {status === 'success' ? <CheckCircle className="w-5 h-5" /> : <UploadCloud className="w-5 h-5" />}
                </div>
            </div>

            <div className={`w-full h-32 border-2 border-dashed rounded-lg flex flex-col items-center justify-center transition-colors cursor-pointer relative
                ${status === 'error' ? 'border-pro-danger bg-pro-danger/5' : 'border-gray-600 hover:border-gray-400 hover:bg-gray-800/50'}`}>

                <input
                    type="file"
                    accept={accept}
                    onChange={handleUpload}
                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                    disabled={status === 'uploading'}
                />

                {status === 'uploading' ? (
                    <div className="text-pro-accent animate-pulse font-medium">Uploading...</div>
                ) : (
                    <>
                        <FileText className="w-8 h-8 text-gray-500 mb-2" />
                        <span className="text-sm text-gray-400">Click or Drag CSV Here</span>
                    </>
                )}
            </div>

            {message && (
                <div className={`mt-3 text-sm flex items-center gap-2 ${status === 'success' ? 'text-pro-success' : 'text-pro-danger'}`}>
                    {status === 'error' && <AlertCircle className="w-4 h-4" />}
                    {message}
                </div>
            )}
        </div>
    );
};

const DataIngestPage = () => {
    return (
        <div className="p-6 space-y-8">
            <div>
                <h1 className="text-3xl font-bold text-white">Data Ingestion</h1>
                <p className="text-gray-400 mt-2">Upload external watchlists and screener data for the engine to process.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <UploadCard
                    title="ChatGPT / AI Drops"
                    endpoint="chatgpt"
                    description="Upload custom watchlists generated by your AI sessions."
                    accept=".csv"
                />

                <UploadCard
                    title="TradingView Exports"
                    endpoint="tradingview"
                    description="Import your exported watchlists from TradingView."
                    accept=".csv"
                />

                <UploadCard
                    title="Finviz Screener"
                    endpoint="finviz"
                    description="Upload mass screener results from Finviz."
                    accept=".csv"
                />
            </div>

            <div className="bg-pro-card p-6 rounded-xl border border-gray-700">
                <h3 className="text-lg font-bold text-white mb-2">Instructions</h3>
                <ul className="list-disc list-inside text-gray-400 space-y-1 text-sm">
                    <li>Files must be in <strong>.csv</strong> format.</li>
                    <li>Uploaded files are saved to the <code>/uploads</code> directory on the server.</li>
                    <li>The engine can be configured to auto-scan these folders for new symbols.</li>
                </ul>
            </div>
        </div>
    );
};

export default DataIngestPage;
